name: Sync Newsky Flights to Supabase

on:
  schedule:
    - cron: '*/40 * * * *'  # every 40 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: windows-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        
      - name: Call Supabase Edge Function
  run: |
    Invoke-RestMethod -Uri "https://kqhcvhbdekcyiyorracs.supabase.co/functions/v1/sync-newsky-flights" `
    -Method POST `
    -Headers @{
        "Authorization" = "Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
        "Content-Type" = "application/json"
    }
