name: Sync Newsky Flights to Supabase

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        
      - name: Call Supabase Edge Function
        run: |
          curl -X POST "https://kqhcvhbdekcyiyorracs.supabase.co/functions/v1/sync-newsky-flights" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"

